import { NextResponse } from "next/server"
import { prisma } from "@/lib/prisma"
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const body = await request.json()
  const permission = await prisma.userPermission.upsert({
    where: { userId: id },
    create: {
      userId: id,
      specView:     body.specView     ?? true,
      specEdit:     body.specEdit     ?? false,
      estimateView: body.estimateView ?? true,
      estimateEdit: body.estimateEdit ?? false,
      eappView:     body.eappView     ?? true,
      eappEdit:     body.eappEdit     ?? false,
      travelView:   body.travelView   ?? true,
      travelEdit:   body.travelEdit   ?? false,
      sopView:      body.sopView      ?? true,
      sopEdit:      body.sopEdit      ?? false,
      reportView:   body.reportView   ?? true,
      reportEdit:   body.reportEdit   ?? false,
      bpmsView:     body.bpmsView     ?? true,
      bpmsEdit:     body.bpmsEdit     ?? false,
      dlmsView:     body.dlmsView     ?? true,
      dlmsEdit:     body.dlmsEdit     ?? false,
      dppView:      body.dppView      ?? true,
      dppEdit:      body.dppEdit      ?? false,
      ssssView:     body.ssssView     ?? true,
      ssssEdit:     body.ssssEdit     ?? false,
      mastersView:  body.mastersView  ?? false,
      mastersEdit:  body.mastersEdit  ?? false,
      ssssIsIssuer:            body.ssssIsIssuer            ?? false,
      ssssIsSupplier:          body.ssssIsSupplier          ?? false,
      ssssIsReceiver:          body.ssssIsReceiver          ?? false,
      ssssIsOutsourceReceiver: body.ssssIsOutsourceReceiver ?? false,
    },
    update: {
      ...(body.specView     !== undefined && { specView:     body.specView }),
      ...(body.specEdit     !== undefined && { specEdit:     body.specEdit }),
      ...(body.estimateView !== undefined && { estimateView: body.estimateView }),
      ...(body.estimateEdit !== undefined && { estimateEdit: body.estimateEdit }),
      ...(body.eappView     !== undefined && { eappView:     body.eappView }),
      ...(body.eappEdit     !== undefined && { eappEdit:     body.eappEdit }),
      ...(body.travelView   !== undefined && { travelView:   body.travelView }),
      ...(body.travelEdit   !== undefined && { travelEdit:   body.travelEdit }),
      ...(body.sopView      !== undefined && { sopView:      body.sopView }),
      ...(body.sopEdit      !== undefined && { sopEdit:      body.sopEdit }),
      ...(body.reportView   !== undefined && { reportView:   body.reportView }),
      ...(body.reportEdit   !== undefined && { reportEdit:   body.reportEdit }),
      ...(body.bpmsView     !== undefined && { bpmsView:     body.bpmsView }),
      ...(body.bpmsEdit     !== undefined && { bpmsEdit:     body.bpmsEdit }),
      ...(body.dlmsView     !== undefined && { dlmsView:     body.dlmsView }),
      ...(body.dlmsEdit     !== undefined && { dlmsEdit:     body.dlmsEdit }),
      ...(body.dppView      !== undefined && { dppView:      body.dppView }),
      ...(body.dppEdit      !== undefined && { dppEdit:      body.dppEdit }),
      ...(body.ssssView     !== undefined && { ssssView:     body.ssssView }),
      ...(body.ssssEdit     !== undefined && { ssssEdit:     body.ssssEdit }),
      ...(body.mastersView  !== undefined && { mastersView:  body.mastersView }),
      ...(body.mastersEdit  !== undefined && { mastersEdit:  body.mastersEdit }),
      ...(body.ssssIsIssuer            !== undefined && { ssssIsIssuer:            body.ssssIsIssuer }),
      ...(body.ssssIsSupplier          !== undefined && { ssssIsSupplier:          body.ssssIsSupplier }),
      ...(body.ssssIsReceiver          !== undefined && { ssssIsReceiver:          body.ssssIsReceiver }),
      ...(body.ssssIsOutsourceReceiver !== undefined && { ssssIsOutsourceReceiver: body.ssssIsOutsourceReceiver }),
    },
  })
  return NextResponse.json(permission)
}
