-- CreateTable
CREATE TABLE "prinser_m_tokui" (
    "tokuisaki_cd" TEXT NOT NULL,
    "siten_cd" TEXT NOT NULL,
    "tokuicd" TEXT,
    "tokuinm" TEXT,
    "tokuinm2" TEXT,
    "tokuinm3" TEXT,
    "ryk_nm" TEXT,
    "tokuikana" TEXT,
    "del_flg" INTEGER,
    "dtindt" TEXT,
    "dtintm" TEXT,
    "dtupdt" TEXT,
    "dtuptm" TEXT,
    "aitesaki_bumon_kanji" TEXT,
    "aitesaki_tantosya" TEXT,
    "aitesaki_address1" TEXT,
    "aitesaki_address2" TEXT,
    "aitesaki_address3" TEXT,
    "aitesaki_yubin_no" TEXT,
    "aitesaki_tel_no" TEXT,
    "tantosya_cd" TEXT,
    "tiiki_cd" TEXT,
    "gyosyu_cd" TEXT,
    "best_juni" TEXT,
    "kyakusaki_bunrui" TEXT,
    "gaityu_bunrui" TEXT,
    "nokyo_kbn" TEXT,
    "sime_date" TEXT,
    "zei_kbn" TEXT,
    "aitesaki_kbn" TEXT,
    "hon_kari_kbn" TEXT,
    "president" TEXT,
    "kabu" TEXT,
    "oya_tokui_cd" TEXT,
    "aitesaki_fax_no" TEXT,
    "group_tokui_cd" TEXT,
    "seikyum_cd" TEXT,
    "furikomis_cd" TEXT,
    "tmail" TEXT,
    "kagami_flg" TEXT,
    "ky_mon" TEXT,
    "ky_dt" TEXT,
    "zzan_sei_flg" TEXT,
    "ny_houhou" TEXT,
    "ny_kamoku_cd" TEXT,
    "nykoza_cd" TEXT,
    "fx4_tokui_cd" TEXT,
    "hasu_kbn" TEXT,
    "shohizei_kbn" TEXT,
    "syk_yobi_flg" TEXT,
    "mitsumorisho_id" TEXT,
    "mitsumori_calc_id" TEXT,
    "syukin_syubetu1" TEXT,
    "syukin_koza1" TEXT,
    "syukin_syubetu2" TEXT,
    "syukin_koza2" TEXT,
    "syukin_tani" TEXT,
    "syukin_kingaku" TEXT,
    "kin_hasu_kbn" TEXT,
    "zei_marume_tani" TEXT,
    "mototyo_vis_flg" TEXT,
    "sony_flg" TEXT,
    "nohon_kensa_kikaku_id" TEXT,
    "seikyu_kbn" TEXT,
    "non_entertainment_flg" TEXT,
    "smc_online_flg" TEXT,
    "rawData" TEXT,
    "importedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "prinser_m_tokui_pkey" PRIMARY KEY ("tokuisaki_cd","siten_cd")
);
